version: '3'
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - '8000:5000'
    environment:
      - SECRET_KEY
      - DATABASE_URL

  db:
    image: mysql/mysql-server:8.0.13
    environment: 
      - DATABASE_URL
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
