version: '3'
services:
  web:
    depends_on:
      - db
    build: .
    ports:
      - '8000:5000'
    environment:
      - SECRET_KEY
      - DATABASE_URL
    volumes:
      - mysql_db:/var/lib/mysql

  db:
    # A lot of useful comments under Github issue about MySQL error 1044 'Access denied':
    # https://github.com/docker-library/mysql/issues/51
    # MySQL docs about setting up Docker container:
    # https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html
    image: mysql/mysql-server:8.0.13
    environment: 
      - DATABASE_URL
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql_db:/var/lib/mysql

# See SO discussion for more details: https://stackoverflow.com/q/44284484
volumes:
  mysql_db: