"""add user tokens

Revision ID: 13a16d8c9963
Revises: 2e4b240ffc47
Create Date: 2020-03-26 20:40:12.282994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a16d8c9963'
down_revision = '2e4b240ffc47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('api_token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_api_token'), 'user', ['api_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_token'), table_name='user')
    op.drop_column('user', 'api_token_expiration')
    op.drop_column('user', 'api_token')
    # ### end Alembic commands ###
