"""rename id to id_

Revision ID: 2e4b240ffc47
Revises: d59937ea0cf7
Create Date: 2020-03-22 15:20:31.359923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e4b240ffc47'
down_revision = 'd59937ea0cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'id')
    op.drop_constraint('fk_post_author_id_user', 'post', type_='foreignkey')
    op.drop_column('user', 'id')
    # See some additional info why this implemented in raw SQL here:
    # https://stackoverflow.com/q/13756567
    op.execute('ALTER TABLE user ADD id_ INT PRIMARY KEY AUTO_INCREMENT;')
    op.execute('ALTER TABLE post ADD id_ INT PRIMARY KEY AUTO_INCREMENT;')
    op.create_foreign_key(
        op.f('fk_post_author_id_user'),
        'post',
        'user',
        ['author_id'],
        ['id_'],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'id_')
    op.drop_constraint(op.f('fk_post_author_id_user'), 'post', type_='foreignkey')
    op.drop_column('user', 'id_')
    # See some additional info why this implemented in raw SQL here:
    # https://stackoverflow.com/q/13756567
    op.execute('ALTER TABLE user ADD id INT PRIMARY KEY AUTO_INCREMENT;')
    op.execute('ALTER TABLE post ADD id INT PRIMARY KEY AUTO_INCREMENT;')
    op.create_foreign_key(
        'fk_post_author_id_user',
        'post',
        'user',
        ['author_id'],
        ['id'],
    )
    # ### end Alembic commands ###
