"""Rename password field

Revision ID: d59937ea0cf7
Revises: 78ab195fc183
Create Date: 2020-03-19 23:26:50.795118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59937ea0cf7'
down_revision = '78ab195fc183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=120), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=120), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
