"""Add 'first_name', 'last_name' fields to User

Revision ID: dd3a97993e05
Revises: d9930013273f
Create Date: 2020-03-09 16:06:16.387403

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd3a97993e05'
down_revision = 'd9930013273f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column(
        'first_name',
        sa.String(length=80),
        nullable=False,
        server_default='')
    )
    op.add_column('user', sa.Column(
        'last_name',
        sa.String(length=80),
        nullable=False,
        server_default='')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
